/*
 * JaamSim Discrete Event Simulation
 * Copyright (C) 2018 JaamSim Software Inc.
 * TypeScript への移植 (C) 2026 shota
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Java の interface は、TS の interface と同じ名前の const の組にした（ProcessFlow/QueueUser.ts と同じ作り）。
// `Controllable.register(クラス)` で印を付け、`x instanceof Controllable` で判定する。
// 判定の関数 isControllable(x) もある（JaamSimModel.getClonesOfIterator(Entity, isControllable) に渡す）。

import type { JClass } from "../java/lang.ts";
import type { Controller } from "./Controller.ts";

const MARK = Symbol("Controllable");

export interface Controllable {

	/**
	 * Returns the Controller that signals the updating of this object.
	 * @return Controller for this object
	 */
	getController(): Controller | null;

	/**
	 * Returns the sequence number that determines the order in which the Controller's objects
	 * are updated. Objects with smaller sequence numbers are updated before ones with larger
	 * numbers.
	 * @return sequence number
	 */
	getSequenceNumber(): number;

	/**
	 * Executes the update for this object that is generated by the Controller.
	 * @param simTime - present simulation time
	 */
	update(simTime: number): void;

}

export const Controllable = {
	/** Java の完全な名前（InterfaceEntityInput などに渡すため） */
	javaName: "com.jaamsim.CalculationObjects.Controllable",

	isInstance(o: unknown): o is Controllable {
		return o instanceof (Controllable as unknown as JClass);
	},

	/** Java の「implements Controllable」の代わり */
	register(cls: JClass): void {
		(cls.prototype as Record<symbol, unknown>)[MARK] = true;
	},

	[Symbol.hasInstance](o: unknown): o is Controllable {
		return o !== null && typeof o === "object" && (o as Record<symbol, unknown>)[MARK] === true;
	},
};

/** x instanceof Controllable の代わり（関数の形） */
export function isControllable(o: unknown): o is Controllable {
	return o instanceof Controllable;
}
