//@@HEADER@@
import { BooleanProvInput } from "../BooleanProviders/BooleanProvInput.ts";
import { ColourProvInput } from "../ColourProviders/ColourProvInput.ts";
import { KeywordCommand } from "../Commands/KeywordCommand.ts";
import { TextModel, type TessFontKey } from "../DisplayModels/TextModel.ts";
import { SampleInput } from "../Samples/SampleInput.ts";
import { StringProvInput } from "../StringProviders/StringProvInput.ts";
import { Entity } from "../basicsim/Entity.ts";
import { tr } from "../i18n/I18n.ts";
import { ColourInput } from "../input/ColourInput.ts";
import { EntityInput } from "../input/EntityInput.ts";
import { Input } from "../input/Input.ts";
import { InputAgent } from "../input/InputAgent.ts";
import type { InputCallback } from "../input/InputCallback.ts";
import { KeywordIndex } from "../input/KeywordIndex.ts";
import { StringChoiceInput } from "../input/StringChoiceInput.ts";
import { StringInput } from "../input/StringInput.ts";
import { StringListInput } from "../input/StringListInput.ts";
import { UnitTypeInput } from "../input/UnitTypeInput.ts";
import { Vec3dInput } from "../input/Vec3dInput.ts";
import { ClassRegistry } from "../java/ClassRegistry.ts";
import type { Color4d } from "../math/Color4d.ts";
import type { Vec3d } from "../math/Vec3d.ts";
import { DimensionlessUnit } from "../units/DimensionlessUnit.ts";
import { Unit } from "../units/Unit.ts";
import { Editable, KeyEvent } from "./Editable.ts";
import { EditableText } from "./EditableText.ts";
import { EditableTextDelegate } from "./EditableTextDelegate.ts";
import { LateClasses, jint } from "./LateClasses.ts";
import { OverlayEntity } from "./OverlayEntity.ts";
import { TextBasics } from "./TextBasics.ts";
import { TextEntity } from "./TextEntity.ts";

/*
 * 移植の注意:
 * - 画面の座標で受ける handleMouseClicked・handleDrag は、OverlayEntity と同じく
 *   handleOverlayMouseClicked・handleOverlayDrag という名前にした（docs/renamed.md）。
 * - 文字の大きさを測る所（RenderManager）は TextBasics.fontMetrics を使う（null なら位置 0）。
 *   RenderManager.redraw() の呼び出しは消した。描画: 省略（three.js の画面を作るときに）。
 * - FailText の既定 "Input Error" はモデルのファイルに書き出す値でもあるので、tr で包まない。
 */

/**
 * OverylayText displays written text as a 2D overlay on a View window.
 * @author Harry King
 *
 */
export class OverlayText extends OverlayEntity implements TextEntity, EditableText {

	protected readonly formatText: StringInput;

	protected readonly unitType: UnitTypeInput;

	protected readonly unit: EntityInput<Unit>;

	protected readonly dataSource: StringProvInput;

	protected readonly failText: StringInput;

	private readonly fontName: StringChoiceInput;

	private readonly textHeight: SampleInput;

	private readonly fontStyle: StringListInput;

	private readonly fontColor: ColourProvInput;

	private readonly dropShadow: BooleanProvInput;

	private readonly dropShadowColor: ColourProvInput;

	private readonly dropShadowOffset: Vec3dInput;

	private renderText: string | null = null;
	private readonly editableText: EditableTextDelegate;

	constructor() {
		super();

		// ---- Java の初期化ブロック ----
		this.displayModelListInput.clearValidClasses();
		this.displayModelListInput.addValidClass(TextModel);

		this.formatText = new StringInput("Format", Entity.KEY_INPUTS, "%s");
		this.setKeywordDoc(this.formatText, "The fixed and variable text to be displayed, as specified by a Java "
		                     + "format string. "
		                     + "If variable text is to be displayed using the DataSource keyword, "
		                     + "include the appropriate Java format in the text. "
		                     + "For example, %s will display a text output and %.6f will display a "
		                     + "number with six decimal digits of accuracy. "
		                     + "A new line can be started by entering %n. "
		                     + "Note that a % character is generated by entering %%.",
				["'Present speed = %.3f m/s'", "'Present State = %s'",
				 "'First line%nSecond line'"]);
		this.formatText.setCallback(OverlayText.formattextCallback);
		this.addInput(this.formatText);

		this.unitType = new UnitTypeInput("UnitType", Entity.KEY_INPUTS, DimensionlessUnit);
		this.setKeywordDoc(this.unitType, "The unit type for the numerical value to be displayed as "
		                     + "variable text. Set to DimensionlessUnit if the variable text is "
		                     + "non-numeric, such as the state of a Server.",
				["DistanceUnit", "DimensionlessUnit"]);
		this.unitType.setCallback(OverlayText.unittypeCallback);
		this.addInput(this.unitType);

		this.unit = new EntityInput<Unit>(Unit, "Unit", Entity.KEY_INPUTS, null);
		this.setKeywordDoc(this.unit, "The unit in which to express an expression that returns a numeric "
		                     + "value.",
				["m/s"]);
		this.unit.setSubClass(null);
		this.addInput(this.unit);

		this.dataSource = new StringProvInput("DataSource", Entity.KEY_INPUTS, "");
		this.setKeywordDoc(this.dataSource, "An expression that returns the variable text to be displayed. "
		                     + "The expression can return a number that will be formated as text, "
		                     + "or it can return text directly, such as the state of a Server. "
		                     + "An object that returns a number, such as a TimeSeries, can also "
		                     + "be entered.",
				["[Queue1].AverageQueueTime", "[Server1].State",
				 "'[Queue1].QueueLength + [Queue2].QueueLength'",
				 "TimeSeries1"]);
		this.dataSource.setUnitType(DimensionlessUnit);
		this.addInput(this.dataSource);
		this.addSynonym(this.dataSource, "OutputName");

		this.failText = new StringInput("FailText", Entity.KEY_INPUTS, "Input Error");
		this.setKeywordDoc(this.failText, "The text to display if there is any failure while formatting the "
		                     + "variable text or while evaluating the expression.",
				["'Input Error'"]);
		this.addInput(this.failText);

		this.fontName = new StringChoiceInput("FontName", Entity.FONT, -1);
		this.setKeywordDoc(this.fontName, "The font to be used for the text.",
				[ "Arial" ]);
		this.fontName.setChoices(TextModel.validFontNames);
		this.fontName.setDefaultText("TextModel");
		this.addInput(this.fontName);

		this.textHeight = SampleInput.ofInt("TextHeight", Entity.FONT, 0);
		this.setKeywordDoc(this.textHeight, "The height of the font as displayed in the view window. Unit is in pixels.",
				["15"]);
		this.textHeight.setValidRange(0, 1000);
		this.textHeight.setIntegerValue(true);
		this.textHeight.setDefaultText("TextModel");
		this.addInput(this.textHeight);

		this.fontColor = new ColourProvInput("FontColour", Entity.FONT, ColourInput.BLACK);
		this.setKeywordDoc(this.fontColor, "The colour of the text.", []);
		this.fontColor.setDefaultText("TextModel");
		this.addInput(this.fontColor);
		this.addSynonym(this.fontColor, "FontColor");

		this.fontStyle = new StringListInput("FontStyle", Entity.FONT, []);
		this.setKeywordDoc(this.fontStyle, "The font styles to be applied to the text, e.g. Bold, Italic. ",
				[ "Bold" ]);
		this.fontStyle.setValidOptions(TextModel.validStyles);
		this.fontStyle.setCaseSensitive(false);
		this.fontStyle.setDefaultText("TextModel");
		this.addInput(this.fontStyle);

		this.dropShadow = new BooleanProvInput("DropShadow", Entity.FONT, false);
		this.setKeywordDoc(this.dropShadow, "If TRUE, then a drop shadow appears for the text.", []);
		this.dropShadow.setDefaultText("TextModel");
		this.addInput(this.dropShadow);

		this.dropShadowColor = new ColourProvInput("DropShadowColour", Entity.FONT, ColourInput.BLACK);
		this.setKeywordDoc(this.dropShadowColor, "The colour for the drop shadow.", []);
		this.dropShadowColor.setDefaultText("TextModel");
		this.addInput(this.dropShadowColor);
		this.addSynonym(this.dropShadowColor, "DropShadowColor");

		this.dropShadowOffset = new Vec3dInput("DropShadowOffset", Entity.FONT, null);
		this.setKeywordDoc(this.dropShadowOffset, "The { x, y, z } coordinates of the drop shadow's offset, expressed "
		                     + "as a decimal fraction of the text height.",
				[ "0.1 -0.1 0.001" ]);
		this.dropShadowOffset.setDefaultText("TextModel");
		this.addInput(this.dropShadowOffset);

		// ---- Java のコンストラクタの中身 ----
		this.editableText = new EditableTextDelegate();
	}

	static readonly formattextCallback: InputCallback = {
		callback(ent: Entity, inp: Input<unknown>): void {
			(ent as OverlayText).updateFormattextValue();
		},
	} as InputCallback;

	updateFormattextValue(): void {
		this.setText(this.formatText.getValue());
	}

	static readonly unittypeCallback: InputCallback = {
		callback(ent: Entity, inp: Input<unknown>): void {
			(ent as OverlayText).updateUnitypeValue();
		},
	} as InputCallback;

	updateUnitypeValue(): void {
		const ut = this.unitType.getUnitType();
		this.dataSource.setUnitType(ut);
		this.unit.setSubClass(ut);
		this.updateUserOutputMap();
	}

	override setInputsForDragAndDrop(): void {
		super.setInputsForDragAndDrop();

		// Set the displayed text to the entity's name
		InputAgent.applyArgs(this, "Format", this.getName());
	}

	setText(str: string): void {
		this.editableText.setText(str);
	}

	getText(): string {
		return this.editableText.getText();
	}

	acceptEdits(): void {
		this.editableText.acceptEdits();
		const kw = KeywordIndex.formatArgs("Format", this.getText());
		try {
			this.getJaamSimModel().storeAndExecute(new KeywordCommand(this, kw));
		}
		catch (e) {
			const gui = this.getJaamSimModel().getGUIListener();
			if (gui !== null && gui !== undefined)
				gui.invokeErrorDialogBox(tr("Input Error"), (e as Error).message);
		}
	}

	cancelEdits(): void {
		this.editableText.cancelEdits();
	}

	isEditMode(): boolean {
		return this.editableText.isEditMode();
	}

	setEditMode(bool: boolean): void {
		this.editableText.setEditMode(bool);
	}

	getInsertPosition(): number {
		return this.editableText.getInsertPosition();
	}

	getNumberSelected(): number {
		return this.editableText.getNumberSelected();
	}

	copyToClipboard(): void {
		this.editableText.copyToClipboard();
	}

	pasteFromClipboard(): void {
		this.editableText.pasteFromClipboard();
	}

	deleteSelection(): void {
		this.editableText.deleteSelection();
	}

	handleEditKeyPressed(keyCode: number, keyChar: string, shift: boolean, control: boolean, alt: boolean): number {
		if (keyChar === "'") {
			const gui = this.getJaamSimModel().getGUIListener();
			if (gui !== null && gui !== undefined)
				gui.invokeErrorDialogBox(tr("Input Error"), tr(Input.INP_ERR_QUOTE));
			return Editable.CONTINUE_EDITS;
		}
		return this.editableText.handleEditKeyPressed(keyCode, keyChar, shift, control, alt);
	}

	handleEditKeyReleased(keyCode: number, keyChar: string, shift: boolean, control: boolean, alt: boolean): number {
		return this.editableText.handleEditKeyReleased(keyCode, keyChar, shift, control, alt);
	}

	setInsertPosition(pos: number, shift: boolean): void {
		this.editableText.setInsertPosition(pos, shift);
	}

	selectPresentWord(): void {
		this.editableText.selectPresentWord();
	}

	override handleKeyPressed(keyCode: number, keyChar: string, shift: boolean, control: boolean, alt: boolean): boolean {

		// If F2 is pressed, set edit mode
		if (keyCode === KeyEvent.VK_F2) {
			this.setEditMode(true);
			// 描画: 省略（RenderManager.redraw()）
			return true;
		}

		// If not in edit mode, apply the normal action for the keystroke
		if (!this.isEditMode()) {
			const ret = super.handleKeyPressed(keyCode, keyChar, shift, control, alt);
			return ret;
		}

		// If in edit mode, the apply the keystroke to the text
		const result = this.handleEditKeyPressed(keyCode, keyChar, shift, control, alt);
		if (result === Editable.ACCEPT_EDITS) {
			this.acceptEdits();
		}
		else if (result === Editable.CANCEL_EDITS) {
			this.cancelEdits();
		}
		// 描画: 省略（RenderManager.redraw()）
		return true;
	}

	override handleKeyReleased(keyCode: number, keyChar: string, shift: boolean, control: boolean, alt: boolean): void {
		if (this.isEditMode()) {
			this.handleEditKeyReleased(keyCode, keyChar, shift, control, alt);
			return;
		}
		super.handleKeyReleased(keyCode, keyChar, shift, control, alt);
	}

	/** Java の handleMouseClicked(short, int, int, int, int, boolean, boolean, boolean)（名前を変えた） */
	override handleOverlayMouseClicked(count: number, x: number, y: number, windowWidth: number, windowHeight: number,
			shift: boolean, control: boolean, alt: boolean): void {
		if (count > 2)
			return;

		// Double click starts edit mode
		if (!this.isEditMode() && count === 2) {
			this.setEditMode(true);
		}

		if (!this.isEditMode())
			return;

		// Position the insertion point where the text was clicked
		const pos = this.getStringPosition(x, y, windowWidth, windowHeight);
		this.editableText.setInsertPosition(pos, shift);

		// Double click selects a whole word
		if (count === 2)
			this.editableText.selectPresentWord();
	}

	/** Java の handleDrag(int, int, int, int, int, int)（名前を変えた） */
	override handleOverlayDrag(x: number, y: number, startX: number, startY: number, windowWidth: number, windowHeight: number): boolean {
		if (!this.isEditMode())
			return false;

		// Set the start and end of highlighting
		const insertPos = this.getStringPosition(x, y, windowWidth, windowHeight);
		const firstPos = this.getStringPosition(startX, startY, windowWidth, windowHeight);
		this.editableText.setInsertPosition(insertPos, false);
		this.editableText.setNumberSelected(firstPos - insertPos);
		return true;
	}

	/**
	 * Returns the insert position in the present text that corresponds to the specified global
	 * coordinate. Index 0 is located immediately before the first character in the text.
	 * 描画: 文字の大きさを測る関数（TextBasics.fontMetrics）が無ければ 0 を返す。
	 * @param x - global x-coordinate for the specified position
	 * @param y - global y-coordinate for the specified position
	 * @return insert position in the text string
	 */
	getStringPosition(x: number, y: number, windowWidth: number, windowHeight: number): number {
		const metrics = TextBasics.fontMetrics;
		if (metrics === null)
			return 0;
		const height = this.getTextHeight(0.0);
		const fontKey = this.getTessFontKey();
		const size = metrics.getRenderedStringSize(fontKey, height, this.getText());
		const pos = this.getScreenPosition();
		const startX = this.getAlignRight() ? windowWidth - pos.get(0) - size.x : pos.get(0);
		const startY = this.getAlignBottom() ? windowHeight - pos.get(1) - size.y : pos.get(1);
		return metrics.getRenderedStringPosition(fontKey, height, this.getText(), x - startX, -y + startY);
	}

	getRenderText(simTime: number): string {

		// If the object is selected, show the editable text
		if (this.isEditMode())
			return this.getText();

		let siFactor = 1.0;
		if (this.unit.getValue() !== null)
			siFactor = this.unit.getValue()!.getConversionFactorToSI();

		// Default Format
		if (this.formatText.isDefault()) {
			let ret: string | null = this.dataSource.getNextString(this, simTime, siFactor);
			if (ret === null || ret === undefined)
				ret = "null";
			return ret;
		}

		// Dynamic text is to be displayed
		try {
			let ret: string | null = this.dataSource.getNextString(this, simTime, this.formatText.getValue(), siFactor);
			if (ret === null || ret === undefined)
				ret = "null";
			return ret;
		}
		catch (e) {
			// Java: catch (Throwable e)
			return this.failText.getValue();
		}
	}

	override updateGraphics(simTime: number): void {
		super.updateGraphics(simTime);

		// This text is cached because reflection is used to get it, so who knows how long it will take
		const newRenderText = this.getRenderText(simTime);
		if (newRenderText === this.renderText) {
			// Nothing important has changed
			return;
		}

		// The text has been updated
		this.renderText = newRenderText;

	}

	override handleSelectionLost(): void {
		if (this.isEditMode()) {
			this.acceptEdits();
		}
	}

	getCachedText(): string | null {
		return this.renderText;
	}

	getTextModel(): TextModel {
		return this.displayModelListInput.getValue()![0] as TextModel;
	}

	getFontName(): string {
		if (this.fontName.isDefault()) {
			return this.getTextModel().getFontName();
		}
		return this.fontName.getChoice();
	}

	getTextHeight(simTime: number): number {
		if (this.textHeight.isDefault()) {
			return this.getTextModel().getTextHeightInPixels(simTime);
		}
		return jint(this.textHeight.getNextSample(this, simTime));
	}

	getTextHeightString(): string {
		if (this.textHeight.isDefault()) {
			return this.getTextModel().getTextHeightInPixelsString();
		}
		return this.textHeight.getValueString();
	}

	getStyle(): number {
		if (this.fontStyle.isDefault()) {
			return this.getTextModel().getStyle();
		}
		return TextModel.getStyle(this.fontStyle.getValue());
	}

	getTessFontKey(): TessFontKey {
		return { fontName: this.getFontName(), style: this.getStyle() };
	}

	getFontColor(simTime: number): Color4d {
		if (this.fontColor.isDefault()) {
			return this.getTextModel().getFontColor(simTime);
		}
		return this.fontColor.getNextColour(this, simTime);
	}

	isDropShadow(simTime: number): boolean {
		if (this.dropShadow.isDefault()) {
			return this.getTextModel().isDropShadow(simTime);
		}
		return this.dropShadow.getNextBoolean(this, simTime);
	}

	getDropShadowColor(simTime: number): Color4d {
		if (this.dropShadowColor.isDefault()) {
			return this.getTextModel().getDropShadowColor(simTime);
		}
		return this.dropShadowColor.getNextColour(this, simTime);
	}

	getDropShadowOffset(): Vec3d {
		if (this.dropShadowOffset.isDefault()) {
			return this.getTextModel().getDropShadowOffset();
		}
		return this.dropShadowOffset.getValue();
	}

	isBold(): boolean {
		return TextModel.isBold(this.getStyle());
	}

	isItalic(): boolean {
		return TextModel.isItalic(this.getStyle());
	}

	override canLabel(): boolean {
		return false;
	}

}

ClassRegistry.register("com.jaamsim.Graphics.OverlayText", OverlayText);
LateClasses.bind("com.jaamsim.Graphics.OverlayText", OverlayText);
