/*
 * JaamSim Discrete Event Simulation
 * Copyright (C) 2009-2013 Ausenco Engineering Canada Inc.
 * Copyright (C) 2018-2024 JaamSim Software Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * TypeScript への移植 (C) 2026 shota
 */
import { BooleanProvInput } from "../BooleanProviders/BooleanProvInput.ts";
import { KeywordCommand } from "../Commands/KeywordCommand.ts";
import { StringProvInput } from "../StringProviders/StringProvInput.ts";
import { Entity } from "../basicsim/Entity.ts";
import { tr } from "../i18n/I18n.ts";
import { EntityInput } from "../input/EntityInput.ts";
import type { Input } from "../input/Input.ts";
import { InputAgent } from "../input/InputAgent.ts";
import type { InputCallback } from "../input/InputCallback.ts";
import { KeywordIndex } from "../input/KeywordIndex.ts";
import { StringInput } from "../input/StringInput.ts";
import { UnitTypeInput } from "../input/UnitTypeInput.ts";
import { ClassRegistry } from "../java/ClassRegistry.ts";
import { DimensionlessUnit } from "../units/DimensionlessUnit.ts";
import { DistanceUnit } from "../units/DistanceUnit.ts";
import { Unit } from "../units/Unit.ts";
import { LateClasses } from "./LateClasses.ts";
import { TextBasics } from "./TextBasics.ts";

/*
 * 移植の注意:
 * - FailText の既定 "Input Error" はモデルのファイルに書き出す値でもあるので、tr で包まない。
 */

/**
 * The "Text" object displays written text within the 3D model universe.  Both fixed and variable text can be displayed.
 * @author Harry King
 *
 */
export class Text extends TextBasics {

	protected readonly formatText: StringInput;

	protected readonly unitType: UnitTypeInput;

	protected readonly unit: EntityInput<Unit>;

	protected readonly dataSource: StringProvInput;

	private readonly failText: StringInput;

	protected readonly autoSize: BooleanProvInput;

	protected renderText = "";

	constructor() {
		super();

		// ---- Java の初期化ブロック ----
		this.formatText = new StringInput("Format", Entity.KEY_INPUTS, "%s");
		this.setKeywordDoc(this.formatText, "The fixed and variable text to be displayed, as specified by a Java "
		                     + "format string. "
		                     + "If variable text is to be displayed using the DataSource keyword, "
		                     + "include the appropriate Java format in the text. "
		                     + "For example, %s will display a text output and %.6f will display a "
		                     + "number with six decimal digits of accuracy. "
		                     + "A new line can be started by entering %n. "
		                     + "Note that a % character is generated by entering %%.",
				["'Present speed = %.3f m/s'", "'Present State = %s'",
				 "'First line%nSecond line'"]);
		this.formatText.setCallback(Text.formattextCallback);
		this.addInput(this.formatText);

		this.unitType = new UnitTypeInput("UnitType", Entity.KEY_INPUTS, DimensionlessUnit);
		this.setKeywordDoc(this.unitType, "The unit type for the numerical value to be displayed as variable "
		                     + "text. Set to DimensionlessUnit if the variable text is non-numeric "
		                     + "such as the state of a Server.",
				["DistanceUnit", "DimensionlessUnit"]);
		this.unitType.setCallback(Text.unittypeCallback);
		this.addInput(this.unitType);

		this.unit = new EntityInput<Unit>(Unit, "Unit", Entity.KEY_INPUTS, null);
		this.setKeywordDoc(this.unit, "The unit in which to express an expression that returns a numerical "
		                     + "value. For example, if the UnitType input has been set to "
		                     + "DistanceUnit, then the output value could be displayed in kilometres, "
		                     + "instead of meters, by entering km to this keyword.",
				["m/s"]);
		this.unit.setSubClass(null);
		this.addInput(this.unit);

		this.dataSource = new StringProvInput("DataSource", Entity.KEY_INPUTS, "");
		this.setKeywordDoc(this.dataSource, "An expression that returns the variable text to be displayed. "
		                     + "The expression can return a number that will be formated as text, "
		                     + "or it can return text directly, such as the state of a Server.",
				["[Queue1].AverageQueueTime", "[Server1].State",
				 "'[Queue1].QueueLength + [Queue2].QueueLength'",
				 "TimeSeries1"]);
		this.dataSource.setUnitType(DimensionlessUnit);
		this.addInput(this.dataSource);
		this.addSynonym(this.dataSource, "OutputName");

		this.failText = new StringInput("FailText", Entity.KEY_INPUTS, "Input Error");
		this.setKeywordDoc(this.failText, "The text to display if there is any failure while formatting the "
		                     + "variable text or while evaluating the expression.",
				["'Input Error'"]);
		this.addInput(this.failText);

		this.autoSize = new BooleanProvInput("AutoSize", Entity.OPTIONS, true);
		this.setKeywordDoc(this.autoSize, "If TRUE, then the size of the background rectangle is adjusted "
		                     + "whenever the displayed text or its font is changed. "
		                     + "Resizing is performed only when the DataSource input has been left "
		                     + "blank.", []);
		this.addInput(this.autoSize);
	}

	static readonly formattextCallback: InputCallback = {
		callback(ent: Entity, inp: Input<unknown>): void {
			(ent as Text).updateFormattextValue();
		},
	} as InputCallback;

	updateFormattextValue(): void {
		this.setText(this.formatText.getValue()!);
	}

	static readonly unittypeCallback: InputCallback = {
		callback(ent: Entity, inp: Input<unknown>): void {
			(ent as Text).updateUnitypeValue();
		},
	} as InputCallback;

	updateUnitypeValue(): void {
		const ut = this.unitType.getUnitType();
		this.dataSource.setUnitType(ut);
		this.unit.setSubClass(ut);
		this.updateUserOutputMap();
	}

	override setInputsForDragAndDrop(): void {
		super.setInputsForDragAndDrop();

		// Set the displayed text to the entity's name
		InputAgent.applyArgs(this, "Format", this.getName());

		// Set the size to match the text
		this.resizeForText();
	}

	override acceptEdits(): void {
		super.acceptEdits();
		const kwList: KeywordIndex[] = [];
		kwList.push( KeywordIndex.formatArgs("Format", this.getText()) );
		if (this.isAutoSize()) {
			const size = this.getAutoSize(this.getFontName(), this.getStyle(), this.getTextHeight(0.0));
			kwList.push( KeywordIndex.formatVec3dInput(this, "Size", size, DistanceUnit) );
		}
		try {
			this.getJaamSimModel().storeAndExecute(new KeywordCommand(this, ...kwList));
		}
		catch (e) {
			const gui = this.getJaamSimModel().getGUIListener();
			if (gui !== null && gui !== undefined)
				gui.invokeErrorDialogBox(tr("Input Error"), (e as Error).message);
		}
	}

	getRenderText(simTime: number): string {

		// If the object is selected, show the editable text
		if (this.isEditMode())
			return this.getText();

		let siFactor = 1.0;
		if (this.unit.getValue() !== null)
			siFactor = this.unit.getValue()!.getConversionFactorToSI();

		// Default Format
		if (this.formatText.isDefault()) {
			let ret: string | null = this.dataSource.getNextString(this, simTime, siFactor);
			if (ret === null || ret === undefined)
				ret = "null";
			return ret;
		}

		// Dynamic text is to be displayed
		try {
			let ret: string | null = this.dataSource.getNextString(this, simTime, this.formatText.getValue()!, siFactor);
			if (ret === null || ret === undefined)
				ret = "null";
			return ret;
		}
		catch (e) {
			// Java: catch (Throwable e)
			return this.failText.getValue()!;
		}
	}

	isAutoSize(): boolean {
		return this.autoSize.getNextBoolean(this, 0.0) && this.dataSource.isDefault();
	}

	override updateGraphics(simTime: number): void {
		super.updateGraphics(simTime);

		// This text is cached because reflection is used to get it, so who knows how long it will take
		const newRenderText = this.getRenderText(simTime);
		if (newRenderText === this.renderText) {
			// Nothing important has changed
			return;
		}

		// The text has been updated
		this.renderText = newRenderText;
	}

	override getCachedText(): string {
		return this.renderText;
	}

}

ClassRegistry.register("com.jaamsim.Graphics.Text", Text);
LateClasses.bind("com.jaamsim.Graphics.Text", Text);
